-- SchoolFix Supabase schema
-- Run this ONCE in Supabase Dashboard -> SQL Editor.
-- Never put your Supabase service key in this file.

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    username text not null unique,
    password text not null,
    role text not null default 'student'
        check (role in ('student','admin','main_admin')),
    created_at timestamptz not null default now()
);

create table if not exists public.admin_applications (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    username text not null,
    reason text not null,
    status text not null default 'Pending'
        check (status in ('Pending','Approved','Rejected')),
    created_at timestamptz not null default now()
);

create table if not exists public.reports (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    username text not null,
    category text not null,
    location text not null default '',
    message text not null,
    status text not null default 'Pending'
        check (status in ('Pending','Reviewed','In Progress','Resolved','Unreasonable')),
    date timestamptz not null default now(),
    admin_note text not null default ''
);

create table if not exists public.report_photos (
    id bigint generated by default as identity primary key,
    report_id bigint not null references public.reports(id) on delete cascade,
    filename text not null,
    storage_path text not null,
    uploaded_at timestamptz not null default now()
);

create table if not exists public.report_messages (
    id bigint generated by default as identity primary key,
    report_id bigint not null references public.reports(id) on delete cascade,
    user_id bigint references public.users(id) on delete set null,
    username text not null,
    role text not null,
    message text not null,
    date timestamptz not null default now()
);

create index if not exists idx_reports_user_id on public.reports(user_id);
create index if not exists idx_reports_date on public.reports(date desc);
create index if not exists idx_report_photos_report_id on public.report_photos(report_id);
create index if not exists idx_report_messages_report_id on public.report_messages(report_id);
create index if not exists idx_admin_applications_status on public.admin_applications(status);

alter table public.users enable row level security;
alter table public.admin_applications enable row level security;
alter table public.reports enable row level security;
alter table public.report_photos enable row level security;
alter table public.report_messages enable row level security;

insert into storage.buckets (id, name, public)
values ('report-photos', 'report-photos', false)
on conflict (id) do nothing;

-- The Flask server uses the Supabase service-role key.
-- Do NOT expose that key in HTML, JavaScript, GitHub, or the browser.
